version: 2

project_name: qiao

before:
  hooks:
    - go test ./...

builds:
  - id: qiao
    main: ./cmd/qiao
    binary: qiao
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: qiao
    ids:
      - qiao
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: qiao_checksums.txt

changelog:
  use: git
